import { WEEKEND_IDS, type WeekendId } from "./config";
import type { TravelEffort, Trip } from "./types";

/**
 * Curated MVP catalog. Values are illustrative per-person estimates for a
 * Fri–Sun weekend from Bengaluru (travel + stay), expressed as bands rather
 * than live prices. The matching engine only reads these structured fields.
 */

const ALL: WeekendId[] = [...WEEKEND_IDS];

export const TRAVEL_LABELS: Record<TravelEffort, string> = {
  short: "Short travel",
  medium: "Moderate travel",
  long: "Long travel",
};

export const TRIPS: Trip[] = [
  {
    id: "south-goa",
    destination: "South Goa",
    region: "goa",
    types: ["beach", "relaxed"],
    estimated_cost_band: "10k_15k",
    travel: "medium",
    travel_note: "Short flight or overnight train",
    available_weekends: ALL,
    tags: ["Quiet beaches", "Beach shacks", "Sunsets"],
    dealbreaker_conflicts: [],
    description: "Slow beach days and long lunches, away from the party strip.",
  },
  {
    id: "north-goa",
    destination: "North Goa",
    region: "goa",
    types: ["beach", "adventure"],
    estimated_cost_band: "10k_15k",
    travel: "medium",
    travel_note: "Short flight or overnight train",
    available_weekends: ALL,
    tags: ["Beach clubs", "Nightlife", "Water sports"],
    dealbreaker_conflicts: ["no_nightlife"],
    description: "Beach clubs by day and a packed nightlife scene after dark.",
  },
  {
    id: "gokarna",
    destination: "Gokarna",
    region: "gokarna",
    types: ["beach", "nature"],
    estimated_cost_band: "under_10k",
    travel: "medium",
    travel_note: "Overnight bus or train",
    available_weekends: ALL,
    tags: ["Beach hopping", "Coastal paths", "Cafés"],
    dealbreaker_conflicts: [],
    description: "Rugged, less crowded beaches with a laid-back café scene.",
  },
  {
    id: "puducherry",
    destination: "Puducherry",
    region: "puducherry",
    types: ["culture", "beach", "relaxed"],
    estimated_cost_band: "under_10k",
    travel: "medium",
    travel_note: "About 6–7 hours by road",
    available_weekends: ALL,
    tags: ["French Quarter", "Cafés", "Seaside promenade"],
    dealbreaker_conflicts: [],
    description: "Colourful heritage streets, café hopping and an easy seaside pace.",
  },
  {
    id: "varkala",
    destination: "Varkala",
    region: "varkala",
    types: ["beach", "relaxed"],
    estimated_cost_band: "15k_20k",
    travel: "medium",
    travel_note: "Flight to Thiruvananthapuram + drive",
    available_weekends: ["2026-11-13", "2026-11-20", "2026-11-27"],
    tags: ["Cliff-top cafés", "Beach", "Ayurveda"],
    dealbreaker_conflicts: [],
    description: "Cliff-top cafés over a quiet beach, built for doing very little.",
  },
  {
    id: "coorg",
    destination: "Coorg",
    region: "coorg",
    types: ["nature", "relaxed", "mountains"],
    estimated_cost_band: "10k_15k",
    travel: "short",
    travel_note: "About 5–6 hours by road",
    available_weekends: ALL,
    tags: ["Coffee estates", "Waterfalls", "Homestays"],
    dealbreaker_conflicts: [],
    description: "Misty coffee country, estate homestays and slow mornings.",
  },
  {
    id: "chikmagalur",
    destination: "Chikmagalur",
    region: "chikmagalur",
    types: ["mountains", "adventure", "nature"],
    estimated_cost_band: "under_10k",
    travel: "short",
    travel_note: "About 5 hours by road",
    available_weekends: ALL,
    tags: ["Mullayanagiri trek", "Coffee trails", "Viewpoints"],
    dealbreaker_conflicts: ["no_trekking"],
    description: "A sunrise hill trek, then coffee-estate downtime.",
  },
  {
    id: "wayanad",
    destination: "Wayanad",
    region: "wayanad",
    types: ["nature", "relaxed"],
    estimated_cost_band: "10k_15k",
    travel: "medium",
    travel_note: "About 6–7 hours by road",
    available_weekends: ALL,
    tags: ["Forest stays", "Tea gardens", "Lakes"],
    dealbreaker_conflicts: [],
    description: "Green forest stays and tea gardens with nowhere to rush to.",
  },
  {
    id: "nilgiris",
    destination: "Ooty & Coonoor",
    region: "nilgiris",
    types: ["mountains", "relaxed", "nature"],
    estimated_cost_band: "10k_15k",
    travel: "medium",
    travel_note: "About 7 hours by road",
    available_weekends: ALL,
    tags: ["Toy train", "Tea estates", "Cool weather"],
    dealbreaker_conflicts: [],
    description: "Cool hill air, tea estates and the heritage mountain railway.",
  },
  {
    id: "munnar",
    destination: "Munnar",
    region: "munnar",
    types: ["mountains", "nature"],
    estimated_cost_band: "10k_15k",
    travel: "long",
    travel_note: "Most of a day by road",
    available_weekends: ["2026-11-06", "2026-11-13", "2026-11-20"],
    tags: ["Tea hills", "Misty viewpoints", "Plantation walks"],
    dealbreaker_conflicts: [],
    description: "Rolling tea hills and misty viewpoints at the end of a long drive.",
  },
  {
    id: "hampi",
    destination: "Hampi",
    region: "hampi",
    types: ["culture", "adventure"],
    estimated_cost_band: "under_10k",
    travel: "medium",
    travel_note: "Overnight train or bus",
    available_weekends: ALL,
    tags: ["Temple ruins", "Boulder sunsets", "Coracle rides"],
    dealbreaker_conflicts: [],
    description: "Ancient ruins in a boulder landscape, best explored by cycle.",
  },
  {
    id: "mysuru",
    destination: "Mysuru",
    region: "mysuru",
    types: ["culture", "relaxed"],
    estimated_cost_band: "under_10k",
    travel: "short",
    travel_note: "About 3 hours by road",
    available_weekends: ALL,
    tags: ["Palaces", "Markets", "Food trail"],
    dealbreaker_conflicts: [],
    description: "Palaces, markets and an easy food trail, close to home.",
  },
  {
    id: "udaipur",
    destination: "Udaipur",
    region: "udaipur",
    types: ["culture", "relaxed"],
    estimated_cost_band: "15k_20k",
    travel: "long",
    travel_note: "Flight + transfer, most of a day",
    available_weekends: ALL,
    tags: ["Lake palaces", "Old city", "Rooftop dinners"],
    dealbreaker_conflicts: [],
    description: "Lakeside palaces, old-city lanes and rooftop dinners.",
  },
  {
    id: "jaipur",
    destination: "Jaipur",
    region: "jaipur",
    types: ["culture"],
    estimated_cost_band: "15k_20k",
    travel: "medium",
    travel_note: "Flight, about half a day door to door",
    available_weekends: ALL,
    tags: ["Forts", "Bazaars", "Rajasthani food"],
    dealbreaker_conflicts: [],
    description: "Hilltop forts, busy bazaars and big Rajasthani thalis.",
  },
  {
    id: "rishikesh",
    destination: "Rishikesh",
    region: "rishikesh",
    types: ["adventure", "nature", "culture"],
    estimated_cost_band: "15k_20k",
    travel: "long",
    travel_note: "Flight to Dehradun + drive",
    available_weekends: ALL,
    tags: ["River rafting", "Bungee", "Ganga aarti"],
    dealbreaker_conflicts: [],
    description: "White-water rafting and bungee by day, riverside evenings.",
  },
  {
    id: "kudremukh",
    destination: "Kudremukh",
    region: "kudremukh",
    types: ["mountains", "adventure", "nature"],
    estimated_cost_band: "under_10k",
    travel: "medium",
    travel_note: "About 7 hours by road",
    available_weekends: ALL,
    tags: ["Summit trek", "Grasslands", "Camping"],
    dealbreaker_conflicts: ["no_trekking"],
    description: "A full-day trek through rolling grasslands to the summit.",
  },
  {
    id: "dandeli",
    destination: "Dandeli",
    region: "dandeli",
    types: ["adventure", "nature"],
    estimated_cost_band: "under_10k",
    travel: "medium",
    travel_note: "Overnight bus",
    available_weekends: ALL,
    tags: ["White-water rafting", "Kayaking", "Jungle stay"],
    dealbreaker_conflicts: [],
    description: "River rafting and kayaking from a jungle base camp.",
  },
  {
    id: "havelock",
    destination: "Havelock, Andamans",
    region: "andaman",
    types: ["beach", "adventure"],
    estimated_cost_band: "20k_plus",
    travel: "long",
    travel_note: "Flight + ferry",
    available_weekends: ["2026-11-13", "2026-11-27"],
    tags: ["Scuba diving", "Clear water", "Island beaches"],
    dealbreaker_conflicts: ["no_expensive"],
    description: "Clear water, reef dives and island beaches: a bigger trip.",
  },
  {
    id: "alleppey",
    destination: "Alleppey backwaters",
    region: "alleppey",
    types: ["relaxed", "nature"],
    estimated_cost_band: "15k_20k",
    travel: "medium",
    travel_note: "Flight to Kochi + drive",
    available_weekends: ALL,
    tags: ["Houseboat stay", "Backwaters", "Kerala food"],
    dealbreaker_conflicts: [],
    description: "A night on a houseboat drifting through the backwaters.",
  },
];

export function findTrip(id: string): Trip | undefined {
  return TRIPS.find((t) => t.id === id);
}
